#! /usr/bin/env node
require('node-oojs');
require('./module.js');

oojs.define({
    name:'cli',
    deps: {
        command: 'oojs.utility.command'
    },
    $cli: function(){
        //使用command类处理命令行输入
        var result = this.command.getCommand({commandDepth:2});
        var commandArray = result.command;        
        var optionObj = result.option;   

        //获取并运行子命令
        var subCommandName = commandArray[1];
        var subCommandClass = oojs.using('oojs.command.'+subCommandName);
        var subCommand = oojs.create(subCommandClass, optionObj);
        subCommand.run();
    }
});